repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
   - id: pretty-format-rust
- repo: https://github.com/afnanenayet/pre-commit-hooks
  rev: v0.1.0
  hooks:
  - id: pretty-format-toml-taplo
  - id: check-toml-schema-taplo
