repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: ^grammars/.*|^test_data/.*
      - id: end-of-file-fixer
        exclude: ^grammars/.*|^test_data/.*
      - id: trailing-whitespace
        exclude: ^grammars/.*|^test_data/.*
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-rust
        exclude: ^grammars/.*|^test_data/.*
  - repo: https://github.com/afnanenayet/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: pretty-format-toml-taplo
        exclude: ^grammars/.*|^test_data/.*
      - id: check-toml-schema-taplo
        exclude: ^grammars/.*|^test_data/.*
