name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew-release:
    runs-on: macos-latest
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: 'diffsitter'
          templatePath: 'support/homebrew-formula.rb'
          tapRepo: 'afnanenayet/homebrew-tap'
          srcRepo: 'afnanenayet/diffsitter'
          authToken: ${{ secrets.GITHUB_TOKEN }}
